# Generated by Django 4.0 on 2024-04-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoreVersionApk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apk_version', models.CharField(max_length=255)),
                ('apk_name', models.CharField(max_length=255)),
                ('apk_download_url', models.CharField(max_length=255)),
                ('update_content', models.TextField()),
            ],
            options={
                'unique_together': {('apk_name', 'apk_version')},
            },
        ),
    ]
