# Generated by Django 4.0 on 2024-05-08 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apkapps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moreversionapk',
            name='update_content',
        ),
    ]
