# Generated by Django 4.0 on 2024-05-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkapps', '0002_remove_moreversionapk_update_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='moreversionapk',
            name='down_path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moreversionapk',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='moreversionapk',
            name='update_content',
            field=models.TextField(null=True),
        ),
    ]
